# Generated by Django 5.0.1 on 2024-03-07 09:09

import django.db.models.deletion
import django.utils.timezone
import grid.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grid_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('vehical_type', models.CharField(max_length=255)),
                ('vehical_subtype', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('rto', models.CharField(max_length=255)),
                ('rate_od', models.CharField(blank=True, max_length=255, null=True)),
                ('rate_tp', models.CharField(blank=True, max_length=255, null=True)),
                ('rate_net', models.CharField(blank=True, max_length=255, null=True)),
                ('rateuser1_od', models.CharField(blank=True, max_length=255, null=True)),
                ('rateuser1_tp', models.CharField(blank=True, max_length=255, null=True)),
                ('rateuser1_net', models.CharField(blank=True, max_length=255, null=True)),
                ('rateuser2_od', models.CharField(blank=True, max_length=255, null=True)),
                ('rateuser2_tp', models.CharField(blank=True, max_length=255, null=True)),
                ('rateuser2_net', models.CharField(blank=True, max_length=255, null=True)),
                ('rateuser3_od', models.CharField(blank=True, max_length=255, null=True)),
                ('rateuser3_tp', models.CharField(blank=True, max_length=255, null=True)),
                ('rateuser3_net', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('agent_payout', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Grid_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('uploaded_file', models.FileField(default='grid_documents/default.jpg', upload_to=grid.models.grid_doc_path)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehical_Sub_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='grid.product_name', verbose_name='product')),
            ],
        ),
        migrations.CreateModel(
            name='Rto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='grid.state', verbose_name='state')),
            ],
        ),
        migrations.AddField(
            model_name='product_name',
            name='vehical_sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehical_sub_type', to='grid.vehical_sub_type', verbose_name='vehical_sub_type'),
        ),
        migrations.CreateModel(
            name='Vehical_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehical_types', to='grid.product', verbose_name='product')),
            ],
        ),
        migrations.AddField(
            model_name='vehical_sub_type',
            name='vehical_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='grid.vehical_type', verbose_name='vehical_type'),
        ),
    ]
