# Generated by Django 4.2.7 on 2023-12-11 04:36

from django.db import migrations, models
import django.utils.timezone
import grid.models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grid_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('vehical_type', models.CharField(max_length=255)),
                ('vehical_sub_type', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('rto', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=255)),
                ('rate', models.CharField(max_length=255)),
                ('agent_payout', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Grid_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('uploaded_file', models.FileField(default='grid_documents/default.jpg', upload_to=grid.models.grid_doc_path)),
            ],
        ),
    ]
