# Generated by Django 4.2.7 on 2023-12-11 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0002_grid_data_grid_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grid_data',
            old_name='sr_no',
            new_name='vehical_subtype',
        ),
        migrations.RemoveField(
            model_name='grid_data',
            name='vehical_sub_type',
        ),
    ]
