# Generated by Django 4.2.7 on 2023-12-13 04:03

from django.db import migrations, models
import django.utils.timezone
import grid.models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0003_rename_sr_no_grid_data_vehical_subtype_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grid_file',
        ),
        migrations.AddField(
            model_name='grid_data',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='grid_data',
            name='uploaded_file',
            field=models.FileField(default='grid_documents/default.jpg', upload_to=grid.models.grid_doc_path),
        ),
    ]
