# Generated by Django 4.2.7 on 2023-12-13 04:15

from django.db import migrations, models
import django.utils.timezone
import grid.models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0004_delete_grid_file_grid_data_created_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grid_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('uploaded_file', models.FileField(default='grid_documents/default.jpg', upload_to=grid.models.grid_doc_path)),
            ],
        ),
    ]
