# Generated by Django 4.2.7 on 2023-12-13 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0005_grid_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grid_data',
            name='uploaded_file',
        ),
    ]
