# Generated by Django 4.1.1 on 2023-12-24 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0006_remove_grid_data_uploaded_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grid_data',
            old_name='rate',
            new_name='rateuser1',
        ),
        migrations.AddField(
            model_name='grid_data',
            name='rateuser2',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grid_data',
            name='rateuser3',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
