# Generated by Django 4.2.7 on 2023-12-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0007_rename_rate_grid_data_rateuser1_grid_data_rateuser2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid_data',
            name='rate',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
