# Generated by Django 5.0.1 on 2024-02-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0008_grid_data_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grid_data',
            old_name='rate',
            new_name='rate_net',
        ),
        migrations.RenameField(
            model_name='grid_data',
            old_name='rateuser1',
            new_name='rate_od',
        ),
        migrations.RenameField(
            model_name='grid_data',
            old_name='rateuser2',
            new_name='rate_tp',
        ),
        migrations.RenameField(
            model_name='grid_data',
            old_name='rateuser3',
            new_name='rateuser1_net',
        ),
        migrations.AddField(
            model_name='grid_data',
            name='rateuser1_od',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grid_data',
            name='rateuser1_tp',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grid_data',
            name='rateuser2_net',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grid_data',
            name='rateuser2_od',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grid_data',
            name='rateuser2_tp',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grid_data',
            name='rateuser3_net',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grid_data',
            name='rateuser3_od',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grid_data',
            name='rateuser3_tp',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
