# Generated by Django 4.2.7 on 2024-02-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0009_rename_rate_grid_data_rate_net_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid_data',
            name='agent_payout',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grid_data',
            name='rate_net',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grid_data',
            name='rate_od',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grid_data',
            name='rate_tp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grid_data',
            name='rateuser1_net',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grid_data',
            name='rateuser1_od',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grid_data',
            name='rateuser1_tp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grid_data',
            name='rateuser2_net',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grid_data',
            name='rateuser2_od',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grid_data',
            name='rateuser2_tp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grid_data',
            name='rateuser3_net',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grid_data',
            name='rateuser3_od',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grid_data',
            name='rateuser3_tp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grid_data',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
